{% set xorg_name = "libXft" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "2.3.8" %}
{% set sha256 = "5e8c3c4bc2d4c0a40aef6b4b38ed2fb74301640da29f6528154b5009b1c6dd49" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  detect_binary_files_with_prefix: true
  # Would need some library futzing to get the build fully working on Windows:
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x') }}

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ stdlib('c') }}          # [unix]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make  # [unix]
  host:
    - xorg-xorgproto
    - pthread-stubs
    - xorg-util-macros
    - xorg-libx11
    - xorg-libxrender
    - freetype
    - fontconfig
    # Required by freetype at build time
    - zlib
    - expat

test:
  commands:
    {% set lib_idents = [ "Xft" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-{{ lib_ident }}-*.dll exit /b 1  # [win]
    {% endfor %}

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org FreeType library.

extra:
  recipe-maintainers:
    - pkgw
    - epruesse
