{% set xorg_name = "libXft" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "2.3.9" %}
{% set sha256 = "60a25b78945ed6932635b3bb1899a517d31df7456e69867ffba27f89ff3976f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  # Would need some library futzing to get the build fully working on Windows:
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x') }}

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2-pkg-config  # [win]
    - pkg-config  # [unix]
    - gnuconfig                    # [unix]
    - m2-base                      # [win]
    - make                         # [unix]
    - m2-make                      # [win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}          # [unix]
    - {{ compiler('m2w64_c') }}    # [win]
    - autoconf                     # [unix]
    - automake                     # [unix]
    - gettext                      # [unix]
    - libtool                      # [unix]
    - sed                          # [unix]
  host:
    - xorg-xorgproto
    - pthread-stubs
    - xorg-util-macros
    - xorg-libx11
    - xorg-libxrender
    - freetype
    - fontconfig
    # Required by freetype at build time
    - zlib
    - expat

test:
  commands:
    {% set lib_idents = [ "Xft" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so     # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-{{ lib_ident }}-*.dll exit /b 1  # [win]
    {% endfor %}

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxft
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxft
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org FreeType library.

extra:
  recipe-maintainers:
    - pkgw
    - epruesse
