# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TDaZzG3oZGCnnv+H1hPKP7TMl2/Ts+Mv7gt7+m4iPSWxgVmeh3jidppNiH65TD5KRJhCNAVErAj3wkoVJAQ3ts61Aj7bdodPz/LcCZ+JP1Gvlzhx3ZRuZrxOnmyet01VQyBwsUjNi/GLsA4jMxNQlWh/84+Rj38mg0hy4fniG7vGzGCV4AK86JQNG+Z3xuNNGwh9SRpIGiFoAGaAri7V76dVIBO8Sm19i7sCvpnJTuXD/V+wqv7xJgeaU4VOYYTRf0oJ8KwQXMdUTffaIGeYd4auSu2IJbMZOP/ArA+ucZAveueJJl+c8FVwoJvuhce3vofiTz4HdIyZUMJdVxQyc7AKnA9dcx1feRfaOd6X9YaeXUfy8vR+/rmEiUWQKidtLDDHg35qKkzf40M2Y3tn/EufInJ8f5PwLAhPhaxSy/yediwvyBhTjIBq4NT/oh4VnPYHpLvV9NwD4/3Cyl6hrpIp7hOh2KvdRtUxpHYOgHuhf2ejp6eFA1N19LUnd9MdN/MwH3VqNO7OWHtm6E4p79rA69wbAKGFK131GSTTkM+VOkl2G9TErSlKEQbu7/1HuqBRoO+mAy1jFF/bYzL3bR6stsIJbt7XQiA8TPuxUqOnlUfh3TAiq2Vat0XY6ZdvU3MYxWmKzK7tYThM7Vrr3zCN2k5MVdSq+4dNwFRYPCU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
