travis:
  secure:
    BINSTAR_TOKEN: UvXJ9jSI//XXvZKLJ2hC10xrVKEKdF9wwBYBwsvdQzwVGheTtBYPuot7u7dX16coN/NRGKdHM5dugktw2axkxSFANKxpC0rfkS/PanboFu4oDLT77qJE1cz72b9YOwwRAxEBUcqSa5Ix3ChkNEklvBs+FCiZLyMsTyA7RHnoet4SWcRqnZRsF/hTTANkHQloYPTTK4ONoMCXOTWxV9LtvSabPghxHl56TP1Q01E9kWw8JESCc1yxI5ldV6yfiqrA1NH8LnE7oSY5XXU7f8t87xmwMJgaCGZ3w884zuhpdITG12DewnWN+ZZeX/kSL69bDkvgyQDXbhKmvahwkXIYcECnFEUJKcxZW6j7aUpfeQraXfrvRvvuTS9ukrUgpgbVjwxS5SXGyPJbDl+dfq0OrqdWuQwckuZherZJ35IQa/o+kGclXDKhD/pB2itbsC6T0GPstfa6iu1uG12o+6fnXaxYhc6zFU3+YWYyFIvDt95BADI7oRzubTTzJ1pc4ufwhFLnfAZaIH4X8oDYFsrMe6RzLz5XXYn2XPRD/eYJedgLkR8zYVsJsdZVNiyZF8B53x60GdCn2mfiSGRxZlQ+1VrhSanSsJ26o2Ou3735wW2MKX/68hhnRVW70y2qYcGNSFzRYlFyVDr0ifGxDl/4Ww4c6iL8Z5/6hNzDu4kbSNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
